# Generated by Django 3.0.1 on 2019-12-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='star',
        ),
    ]
